# # Example mutations for a simple movie app

# # Create a movie based on user input
# mutation CreateMovie(
#   $title: String!
#   $genre: String!
#   $imageUrl: String!
# ) @auth(level: USER_EMAIL_VERIFIED) {
#   movie_insert(
#     data: {
#       title: $title
#       genre: $genre
#       imageUrl: $imageUrl
#     }
#   )
#

# mutation InsertUser($id: String!, $username: String!) @auth(level: PUBLIC) {
#   user_insert(data: { id: $id, username: $username })
# }
