query ListArticles @auth(level: PUBLIC) {
  articles {
    id
    factSet {
      id
      story {
        id
        status {
          id
          status
        }
        publishedAt
      }
      coreFacts
    }
    generatedContent
    reviewedContent
    hasBeenReviewed
    isLive
  }
}
