extend type FactSet {
  """
  ✨ List `Article` objects in a one-to-many relationship (where `Article`.`factSet` is this object).
  """
  articles_on_factSet(
    """
    Filter condition to narrow down the query results.
    """
    where: Article_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Article_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Article!]! @fdc_generated(from: "Article.factSet", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
}
extend type Story {
  """
  ✨ List `FactSet` objects in a one-to-many relationship (where `FactSet`.`story` is this object).
  """
  factSets_on_story(
    """
    Filter condition to narrow down the query results.
    """
    where: FactSet_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FactSet_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [FactSet!]! @fdc_generated(from: "FactSet.story", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
}
extend type StoryStatus {
  """
  ✨ List `Story` objects in a one-to-many relationship (where `Story`.`status` is this object).
  """
  stories_on_status(
    """
    Filter condition to narrow down the query results.
    """
    where: Story_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Story_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Story!]! @fdc_generated(from: "Story.status", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
}
