# Users
type User @table {
  id: UUID! @col(name: "user_id") @default(expr: "uuidV4()")
  auth: String @col(name: "user_auth") @default(expr: "auth.uid")
  email: String!
  username: String
  isVerifiedJournalist: Boolean! @default(value: false)
}

type StoryStatus @table {
  status: String!
}

# Stories
type Story @table {
  status: StoryStatus!
  publishedAt: Timestamp
}

type FactSet @table(name: "FactSets", key: ["story"]) {
  story: Story!
  coreFact: String!
}

type Article @table(name: "Articles", key: ["factSet"]) {
  factSet: FactSet!
  generatedContent: String!
  reviewedContent: String
  hasBeenReviewed: Boolean! @default(value: false)
  isLive: Boolean! @default(value: false)
}

type ArticleComparison @table {
  articleA: Article!
  articleB: Article!
  articleAUniqueShareCount: Int! @default(value: 0)
  articleBUniqueShareCount: Int! @default(value: 0)
  countThreshold: Int! @default(value: 25)
}
